### ISSUE TITLE
[Gameplay] Acear I spectator spawn

### ISSUE THREAD

**Issue by residal** [Warzone/PublicMaps#83] opened 2022-06-18 01:43 UTC
### Map Name

Acear I 

### Suggestion

Elevate the spawn for spectators so it does not interfere with gameplay. The build height of the map is currently 2-3 blocks below the spectator spawn, which affects skybridges as there is not an adequate amount of breathing room to extend a skybridge and attempt to rush.

**Comment by TheRealPear** [comment] 2022-06-18 02:00
Duplicate of #82

**Comment by BTKingly** [comment] 2022-07-18 03:54
Fixed in [8a2e6d6](https://github.com/Warzone/PublicMaps/commit/8a2e6d6acce6e92ae423fd2690b9904b3e6547f5)

**Closed by BTKingly** 2022-07-18 03:54 UTC
Labels: map, gameplay
